using System.Collections.ObjectModel;

namespace WinttyBench.Cells;

public static class StarredCells
{
    private static IReadOnlyDictionary<string, string> Empty { get; } =
        new ReadOnlyDictionary<string, string>(new Dictionary<string, string>());

    public static IReadOnlyList<Cell> All { get; } =
    [
        new Cell(
            Id: "C1",
            Shell: "pwsh-7.4",
            Workload: "vtebench_dense_cells",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: "fixtures/vtebench/dense_cells.txt",
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        // C2 is split into C2a (pwsh, ~2k B/s user-shell floor) and C2b
        // (wsl `cat`, ~97k B/s fast path) on the same fixture and binary;
        // the ~50x gap is the pwsh+ConPTY ceiling, not a wintty cost.
        new Cell(
            Id: "C2a",
            Shell: "pwsh-7.4",
            Workload: "vtebench_scrolling",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: "fixtures/vtebench/scrolling.txt",
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        new Cell(
            Id: "C2b",
            Shell: "wsl-ubuntu-24.04",
            Workload: "vtebench_scrolling",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: "fixtures/vtebench/scrolling.txt",
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        // C3 is a single baseline cell at MVP (no utf8-console knob yet).
        // When the knob lands (Plan 4), split into C3a (force) and C3b (never).
        new Cell(
            Id: "C3",
            Shell: "pwsh-7.4",
            Workload: "cjk_jp_mixed_1mb",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: "fixtures/cjk/jp-mixed-1mb.txt",
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        new Cell(
            Id: "C4",
            Shell: "wsl-ubuntu-24.04",
            Workload: "vtebench_dense_cells",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: "fixtures/vtebench/dense_cells.txt",
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        new Cell(
            Id: "C5",
            Shell: "wsl-ubuntu-24.04",
            Workload: "vtebench_unicode",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: "fixtures/vtebench/unicode.txt",
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        // C8: pwsh startup latency. Default $PROFILE loads (no -NoProfile);
        // profile load IS what we measure here. Different discipline from
        // C1/C2a throughput cells, which strip profile noise with -NoProfile.
        new Cell(
            Id: "C8",
            Shell: "pwsh-7.4",
            Workload: "shell_startup",
            Kpi: "startup_seconds",
            FixturePath: null,
            FixtureKey: null,
            WinttyConfigOverrides: Empty),

        // C10: sustained real-workload ingest through WSL. Fixture is
        // dense_cells.txt repeated to target size; generated on WSL side
        // by scripts/fixtures/make-c10.sh on first run per (key, size).
        new Cell(
            Id: "C10",
            Shell: "wsl-ubuntu-24.04",
            Workload: "vtebench_cat_sustained",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: null,
            FixtureKey: "c10",
            WinttyConfigOverrides: Empty),

        // C11: sustained parser stress from seeded PRNG restricted to a safe
        // VT grammar (printable ASCII + LF + TAB + small subset of SGR/CUP).
        // Generated by scripts/fixtures/make-c11.sh; seed is constant so
        // the fixture is byte-identical across machines.
        new Cell(
            Id: "C11",
            Shell: "wsl-ubuntu-24.04",
            Workload: "filtered_random_sustained",
            Kpi: "throughput_bytes_per_sec",
            FixturePath: null,
            FixtureKey: "c11",
            WinttyConfigOverrides: Empty),
    ];
}
